services:
  mongo_db:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo_db
    environment:
      - MONGO_URI=mongodb://mongo_db:27017/devops_db
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
    depends_on:
      - backend

volumes:
  mongo-data:
